[MST-40]: JS SDK - Extend integration model type to include MS Teams type 👥
MindscapeHQ/raygunapi-js pull request #19
Opened 2022-11-08 03:25 UTC by sumitramanga

## [MST-40:](https://raygun.atlassian.net/browse/MST-40) [JS SDK] Extend integration model type to include MS Teams type 👥

### Description 📝 
This PR is to implement the MS Teams integration type and add an optional userId parameter to the delete integration endpoint

**Updates**
👉 Modify relevant enums to include MS Teams type
👉 Extend `IIntegration` to include the newly made `IMicrosoftTeamsIntegrationData` type
👉 Add new userId parameter to delete integration endpoint
👉 Bump package number

### Screenshots 📷
{Image here}

### Test plan 🧪 
- Can pass through an MS Teams type into the integration endpoints
- `userId` parameter on delete integration endpoint is optional

### Author to check 👓 
- [ ] Builds pass
- [ ] Tested in an alternative environment
- [ ] Reviewed by another developer
- [ ] Appropriate documentation written (code comments, Quip docs)

### Reviewer to check ✔️ 
- [ ] Change has been tested in a separate environment
- [ ] Code is written to standards
- [ ] Appropriate tests have been written (code comments, Quip docs)

2022-11-08 23:04 UTC, crystalqdm requested changes
Don't forget to add the new `AlertActionSettingType` (: 
Can you please also test the GET endpoint to verify the `teamId` property comes back as null from the public api (as it is a sensitive data property)

2022-11-08 23:04 UTC, crystalqdm commented on lib/entities/integrations/enums.ts
> +  MsTeams = "MsTeams"
I think we mightve made this decision when you were on break, but to standardize things we decided to use the full name `MicrosoftTeams` for any types/ class names etc. (:

2022-11-08 23:04 UTC, crystalqdm commented on lib/entities/integrations/index.ts
> +   * @param userId - Id of the user logged in
Can remove this

2022-11-08 23:04 UTC, crystalqdm commented on package.json
> +  "version": "0.1.63",
should it be `0.1.61` -> `0.1.62` ?

2022-11-08 23:04 UTC, crystalqdm commented on lib/entities/integrations/models.ts
> +  serviceUrl: string | null;
The reason `teamId` can be a null type is because it is a sensitive data property and may come back as null from the public API. `serviceUrl` is not a sensitive property so should never have the null type

2022-11-08 23:07 UTC, sumitramanga commented on lib/entities/integrations/models.ts
> +  serviceUrl: string | null;
Ahhh, that makes sense. Thank you for clarifying that!

2022-11-08 23:08 UTC, sumitramanga commented on lib/entities/integrations/enums.ts
> +  MsTeams = "MsTeams"
Ah yes, I think I was referring to a old PR. Thanks for that

2022-11-09 00:07 UTC, crystalqdm approved these changes
Thanks for the changes! LGTM 🚀

2022-11-09 02:59 UTC, crystalqdm approved these changes
🚀

2022-11-09 21:19 UTC, merged